repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v2.3.0"
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
      - id: check-merge-conflict
      - id: requirements-txt-fixer
  - repo: "https://github.com/psf/black"
    rev: "24.10.0"
    hooks:
      - id: black
  - repo: "https://github.com/pycqa/flake8"
    rev: "7.1.1"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-builtins
          - pep8-naming
  - repo: "https://github.com/PyCQA/bandit"
    rev: "1.7.10"
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: "https://github.com/jendrikseipp/vulture"
    rev: "v2.13"
    hooks:
      - id: vulture
        pass_filenames: true
  - repo: "https://github.com/Yelp/detect-secrets"
    rev: "v1.5.0"
    hooks:
      - id: detect-secrets
        exclude: (allure-report|allure-results|report\.html)
  - repo: https://github.com/djlint/djLint
    rev: "v1.36.1"
    hooks:
      - id: djlint-reformat-django
        exclude: (allure-report|allure-results|report\.html)
