# Generated by Django 5.1.2 on 2024-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_alter_uploadeditem_modified_by_shareditem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadeditem",
            name="file_hash",
            field=models.CharField(max_length=20),
        ),
    ]
